### ISSUE TITLE
SweetAlert2

### ISSUE THREAD

**Issue by limonte** [lishengzxc/vue-sweetalert#1]
The original SweetAlert plugin is currently unsupported, there's [SweetAlert2](https://github.com/limonte/sweetalert2). Consider to base your plugin on it. 

Migration guide: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

**Comment by lishengzxc** [comment]
[https://github.com/lishengzxc/vue-sweetalert/pull/2](https://github.com/lishengzxc/vue-sweetalert/pull/2)

Yep, I have been to change to sweetalert2. Thanks~

**Comment by limonte** [comment]
Thank you @lishengzxc for the quick change! SweetAlert2 is much ahead of original SweetAlert plugin and beside me (author) there are three collaborators which mean project won't be dead.
