### ISSUE TITLE
how to use Sweet Alert to StandAlone Class From Vue Js ?

### ISSUE THREAD

**Issue by webafra** [lishengzxc/vue-sweetalert#10]
hello .

how to use Sweet Alert to StandAlone Class From Vue Js ?

component :
my variable is :  form = new Form() ( On Everywhere it is needed. )

@submit event :
form.submit('post' , '/admin/posts');

Class Form :
submit(request , url){
   // send ajax request 
   // if success , run this.onSuccess() method
   // else run this.OnFail()
}

OnFail(){
  // i want use Sweet Alert it here .
}

**Comment by lishengzxc** [comment]
@m-alinasab you can use https://github.com/limonte/sweetalert2 directly~
