### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '$swal' of undefined

### ISSUE THREAD

**Issue by ranaclyde** [lishengzxc/vue-sweetalert#13]
This error occurs (in then or catch) when I run two nested sweetalerts

```
      this.$swal({
        title: 'Are you sure?',
        text: 'You will not be able to recover this imaginary file!',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, delete it!',
        cancelButtonText: 'No, keep it'
      }).then(function () {
        this.$swal(
          'Deleted!',
          'Your imaginary file has been deleted.',
          'success'
        )
      }, function (dismiss) {
        // dismiss can be 'overlay', 'cancel', 'close', 'esc', 'timer'
        if (dismiss === 'cancel') {
          this.$swal(
            'Cancelled',
            'Your imaginary file is safe :)',
            'error'
          )
        }
      })
```

some help?

**Comment by ranaclyde** [comment]
[@lgraziani2712](https://github.com/lgraziani2712) helped me with this issue.

Solution with fat arrow:

```
this.$swal({
        title: 'Are you sure?',
        text: 'You will not be able to recover this imaginary file!',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, delete it!',
        cancelButtonText: 'No, keep it'
      }).then(() => (
        this.$swal('Deleted!', 'Your imaginary file has been deleted.', 'success'))
      ).catch(dismiss => (dismiss !== 'cancel' ? undefined : this.$swal('Cancelled', 'Your imaginary file is safe :)', 'error')))
```

Therefore, I close this issue 👍

**Comment by mbj36** [comment]
Any idea why it works with fat arrow functions ?

**Comment by ranaclyde** [comment]
It has to do with the scope of the variables. When you create a function, you change the scope of the variables

**Comment by toverux** [comment]
aha, this is a common problem with class-components-based frameworks :smile: 
Read this for more : https://github.com/limonte/sweetalert2/issues/630#issuecomment-331239542
`() => {}` is _not_ the same as `function() {}`. It's the same as `(function() {}).bind(this)`.

**Comment by mateusvg** [comment]
For me it work like this:

    delete() {
    this.$swal({
        title: "$titleWarnignBox",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#36c6d3",
        cancelButtonColor: "#d33",
        confirmButtonText: "$confrimBtn",
        cancelButtonText: "$cancelBtn",
      }).then((result) =>  {
        if (result.value) {
          this.$swal(
            "Deleted!",
            "Your imaginary file has been deleted.",
            "success"
          )
          console.log("good");
        } else if (result.dismiss == "cancel") {
          this.$swal("Cancelled", "Your imaginary file is safe :)", "error")
          console.log("cancel");
        }
      });
    },
