### ISSUE TITLE
Dep update

### ISSUE THREAD

**Issue by bbashy** [lishengzxc/vue-sweetalert#8]
Can you upgrade this to the latest on sweetalert2? 5.3.8 has a fix for bootstrap's .fade class.

Ref: https://github.com/limonte/sweetalert2/commit/3f36267445a0b8e365ab2c7112a8d6b1ccf4622a

**Comment by CasperLaiTW** [comment]
I sent PR #7

**Comment by bbashy** [comment]
@CasperLaiTW I know. Just letting them know it's a bit problem 👍

**Comment by AshboDev** [comment]
Any idea when this will be upgraded and @CasperLaiTW's PR merged?

**Comment by CasperLaiTW** [comment]
Hi, @AshboDev 

You can use my [fork](https://github.com/CasperLaiTW/vue-sweetalert.git) until PR merged.

**Comment by bbashy** [comment]
Fixed in bd9758841c8fa045272574ca42d553482d84989e
